# Prometheus配置文件

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-manager'

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Docker Manager API监控
  - job_name: 'docker-manager-api'
    static_configs:
      - targets: ['docker-manager:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Node Exporter（如果部署）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor容器监控（如果部署）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis监控（如果有Redis Exporter）
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # PostgreSQL监控（如果有Postgres Exporter）
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Nginx监控（如果有Nginx Exporter）
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Docker Engine监控（如果启用了metrics）
  - job_name: 'docker-engine'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 15s
    metrics_path: /metrics

# 告警管理器配置（如果使用）
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# 远程写入配置（如果需要）
# remote_write:
#   - url: "http://remote-storage:9201/write"

# 远程读取配置（如果需要）
# remote_read:
#   - url: "http://remote-storage:9201/read"